# 1. Imagen base con Node.js 22.14
FROM node:22.14

# 2. Establecer el directorio de trabajo dentro del contenedor
WORKDIR /usr/src/app

# 3. Copiar los archivos de dependencias
COPY package*.json ./

# 4. Instalar dependencias
RUN npm install

# 5. Copiar el resto del código
COPY dist ./dist

# 6. Exponer el puerto que usará la app
EXPOSE 3000

# 7. Comando para ejecutar la app
CMD ["node", "dist/main.js"]
